"""
Initialize examples package
"""

from examples.example_queries import (
    SALES_QUERIES,
    CUSTOMER_QUERIES,
    PRODUCT_QUERIES,
    ORDER_QUERIES,
    REVIEW_QUERIES,
    PAYMENT_QUERIES,
    ADVANCED_QUERIES,
    TRANSLATION_QUERIES,
    KNOWLEDGE_QUERIES,
    CONVERSATIONAL_EXAMPLES
)

__all__ = [
    'SALES_QUERIES',
    'CUSTOMER_QUERIES',
    'PRODUCT_QUERIES',
    'ORDER_QUERIES',
    'REVIEW_QUERIES',
    'PAYMENT_QUERIES',
    'ADVANCED_QUERIES',
    'TRANSLATION_QUERIES',
    'KNOWLEDGE_QUERIES',
    'CONVERSATIONAL_EXAMPLES'
]
